workspace:
  base: /rotbd
  path: src/${DRONE_REPO_SLUG}

pipeline:
  deploy:
    image: appleboy/drone-ssh
    host: 188.166.61.106
    user: root
    username: root
    port: 22
    key: ${SSH_KEY}
    when:
      event: 
        - push
        - tag
    script:
      - cd ~/battlezone/rotbd
      - git fetch
      - git checkout ${DRONE_BRANCH}
      - git reset --hard
      - git pull
      - mkdir ~/battlezone/tmp_files
      - find ~/battlezone/rotbd -not -iwholename '*/\.*' -type f -exec rsync -rv {} ~/battlezone/tmp_files \;
      - mkdir -p ~/battlezone/builds/${DRONE_BRANCH}
      - FILE_COUNT=$(ls ~/battlezone/builds/${DRONE_BRANCH} | wc -l)
      - mv ~/battlezone/builds/${DRONE_BRANCH}/rotbd_latest_${DRONE_TAG}.zip ~/battlezone/builds/${DRONE_BRANCH}/rotbd_"$FILE_COUNT"_${DRONE_TAG}.zip
      - zip -j -r ~/battlezone/builds/${DRONE_BRANCH}/rotbd_latest_${DRONE_TAG}.zip ~/battlezone/tmp_files
      - find -type f -name '*.bzn' -exec python3 ~/battlezone/tmp_files/bznDown.py {} {} \;
      - mv ~/battlezone/builds/${DRONE_BRANCH}/rotbd1.5c_latest_${DRONE_TAG}.zip ~/battlezone/builds/${DRONE_BRANCH}/rotbd1.5c_"$FILE_COUNT"_${DRONE_TAG}.zip
      - zip -j -r ~/battlezone/builds/${DRONE_BRANCH}/rotbd1.5c_latest_${DRONE_TAG}.zip ~/battlezone/tmp_files
      - rm -rf ~/battlezone/tmp_files


