workspace:
  base: /rotbd
  path: /${DRONE_REPO_SLUG}/

pipeline:
  pre-process:
    image: docker.faavne.no/bzone/bztools:latest
    pull: true
    when:
      event:
        - push
        - tag

    commands:
      - mkdir /tmp/files
      - mkdir /tmp/lua
      - find /rotbd -type f \( -name "*.lua" -o -name "*.squish" \) -exec cp {} /tmp/lua \;
      - python3 /bztools/luaSquish.py /tmp/lua -r
      - find /rotbd -not -ipath '*/\.*' -not -name '*.lua' -not -name '*.bin' -type f -exec cp {} /tmp/files \;
      - find /tmp/lua -name '*.lua' -type f -exec mv {} /tmp/files \;
      - python3 /bztools/textToSpeech.py /tmp/files
      - python3 /bztools/crlf_fixer.py /tmp/files
      - mkdir -p /rotbd/output
      - zip -j -r /rotbd/output/bundle.zip /tmp/files
      - find -type f -name '*.bzn' -exec python3 /bztools/bznDown.py {} {} \;
      - zip -j -r /rotbd/output/bundle1.5.zip /tmp/files


  upload:
    image: appleboy/drone-scp
    host: faavne.no
    username: root
    secrets: [ssh_key]
    key_path: /ssh/id_rsa
    target:
      - /tmp/
    source:
      - /rotbd/output/bundle.zip
      - /rotbd/output/bundle1.5.zip
    strip_components: 2

    volumes:
      - /root/.ssh/id_rsa:/ssh/id_rsa

  snapshot-branch:
    group: deploy
    image: appleboy/drone-ssh
    host: faavne.no
    username: root
    key_path: /ssh/id_rsa
    secrets: [ssh_key]
    when:
      event:
        - push
        
    script:
      - mkdir -p /mnt/nginx-fs/files/private/rotbd/builds/branches/${DRONE_BRANCH} || true
      - FILE_COUNT=$(ls /mnt/nginx-fs/files/private/rotbd/builds/branches/${DRONE_BRANCH} | wc -l) || true
      - mv /mnt/nginx-fs/files/private/rotbd/builds/branches/${DRONE_BRANCH}/rotbd_latest.zip /mnt/nginx-fs/files/private/rotbd/builds/branches/${DRONE_BRANCH}/rotbd_"$FILE_COUNT".zip || true
      - cp /tmp/bundle.zip /mnt/nginx-fs/files/private/rotbd/builds/branches/${DRONE_BRANCH}/rotbd_latest.zip || true
      - mv /mnt/nginx-fs/files/private/rotbd/builds/branches/${DRONE_BRANCH}/rotbd1.5c_latest.zip /mnt/nginx-fs/files/private/rotbd/builds/branches/${DRONE_BRANCH}/rotbd1.5c_"$FILE_COUNT".zip || true
      - cp /tmp/bundle1.5.zip /mnt/nginx-fs/files/private/rotbd/builds/branches/${DRONE_BRANCH}/rotbd1.5c_latest.zip || true


    volumes:
      - /root/.ssh/id_rsa:/ssh/id_rsa

  release:
    group: deploy
    image: appleboy/drone-ssh
    host: faavne.no
    username: root
    key_path: /ssh/id_rsa
    secrets: [ssh_key]
    when:
      event:
        - tag
    script:
      - cp -f /tmp/bundle.zip /mnt/nginx-fs/files/private/rotbd/builds/branches/rotbd_${DRONE_TAG}.zip
      - cp -f /tmp/bundle1.5.zip /mnt/nginx-fs/files/private/rotbd/builds/branches/rotbd1.5c_${DRONE_TAG}.zip
      - ln -f /mnt/nginx-fs/files/private/rotbd/builds/branches/rotbd_${DRONE_TAG}.zip /mnt/nginx-fs/files/private/rotbd/builds/branches/rotbd_latest.zip
      - ln -f /mnt/nginx-fs/files/private/rotbd/builds/branches/rotbd1.5c_${DRONE_TAG}.zip /mnt/nginx-fs/files/private/rotbd/builds/branches/rotbd1.5c_latest.zip

  notification-success:
    image: docker.faavne.no/bzone/bztools:latest
    secrets: [ webhook ]
    when:
      event: [ tag ]
      status: [ success ]
    commands:
      - python3 /bztools/webhook.py /rotbd/.webhook.payload $${WEBHOOK} -kv "status=SUCCESS" "tag=${DRONE_TAG}" "buildlink=${DRONE_BUILD_LINK}" "repolink=${DRONE_REPO_LINK}" "repo=${DRONE_REPO_NAME}" "event=${DRONE_BUILD_EVENT}"
  
  notification-fail:
    image: docker.faavne.no/bzone/bztools:latest
    secrets: [ webhook ]
    when:
      event: [ tag ]
      status: [ fail ]
    commands: 
      - python3 /bztools/webhook.py /rotbd/.webhook.fail $${WEBHOOK} -kv "status=FAIL" "tag=${DRONE_TAG}" "buildlink=${DRONE_BUILD_LINK}" "repolink=${DRONE_REPO_LINK}" "repo=${DRONE_REPO_NAME}" "event=${DRONE_BUILD_EVENT}"
    

