workspace:
  base: /rotbd
  path: src/${DRONE_REPO_SLUG}

pipeline:
  pre-process:
    image: docker.studynator.me/bzone/bztools:latest
    when:
      event:
        - push
        - tag
        
    commands:
      - mkdir ./tmp_files
      - find /rotbd -not -ipath '*/\.*' -type f -exec rsync -rv {} ./tmp_files \;
      - python3 /bztools/crlf_fixer.py ./tmp_files
      - mkdir -p /rotbd/output
      - zip -j -r /rotbd/output/bundle.zip ./tmp_files
      - find -type f -name '*.bzn' -exec python3 /bztools/bznDown.py {} {} \;
      - zip -j -r /rotbd/output/bundle1.5.zip ./tmp_files

  snapshot-branch:
    group: deploy
    image: ubuntu
    when:
      event:
        - push
        
    commands:
      - mkdir -p /drone/deploy/${DRONE_BRANCH} || true
      - FILE_COUNT=$(ls /drone/deploy/${DRONE_BRANCH} | wc -l) || true
      - mv /drone/deploy/${DRONE_BRANCH}/rotbd_latest.zip /drone/deploy/${DRONE_BRANCH}/rotbd_"$FILE_COUNT".zip || true
      - cp /rotbd/output/bundle.zip /drone/deploy/${DRONE_BRANCH}/rotbd_latest.zip || true
      - mv /drone/deploy/${DRONE_BRANCH}/rotbd_latest1.5c.zip /drone/deploy/${DRONE_BRANCH}/rotbd1.5c_"$FILE_COUNT".zip || true
      - cp /rotbd/output/bundle1.5.zip /drone/deploy/${DRONE_BRANCH}/rotbd1.5c_latest.zip || true
    volumes:
      - /root/studynator/nginx-fs/private/rotbd/builds/branches:/drone/deploy

  release:
    group: deploy
    image: ubuntu
    when:
      event:
        - tag
    commands:
      - \cp -f /rotbd/output/bundle.zip /drone/deploy/rotbd_${DRONE_TAG}.zip || true
      - \cp -f /rotbd/output/bundle1.5.zip /drone/deploy/rotbd1.5c_${DRONE_TAG}.zip || true
    volumes:
      - /root/studynator/nginx-fs/private/rotbd/builds/releases:/drone/deploy
