workspace:
  base: /rotbd
  path: src/${DRONE_REPO_SLUG}

pipeline:
  pre-process:
    image: builder
    when:
      event:
        - push
    commands:
      - mkdir ./tmp_files
      - find /rotbd -not -iwholename '*/\.*' -type f -exec rsync -rv {} ./tmp_files \;
      - mkdir -p /rotbd/output
      - zip -j -r /rotbd/output/bundle.zip ./tmp_files
      - find -type f -name '*.bzn' -exec python3 ./tmp_files/bznDown.py {} {} \;
      - zip -j -r /rotbd/output/bundle1.5.zip ./tmp_files

  snapshot-branch:
    image: ubuntu
    when:
      event:
        - push
    commands:
      - FILE_COUNT=$(ls /drone/deploy/${DRONE_BRANCH} | wc -l)
      - mv /drone/deploy/${DRONE_BRANCH}/rotbd_latest.zip /drone/deploy/${DRONE_BRANCH}/rotbd_"$FILE_COUNT".zip
      - cp /rotbd/output/bundle.zip /drone/deploy/${DRONE_BRANCH}/rotbd_latest.zip
      - mv /drone/deploy/${DRONE_BRANCH}/rotbd_latest1.5c.zip /drone/deploy/${DRONE_BRANCH}/rotbd1.5c_"$FILE_COUNT".zip
      - cp /rotbd/output/bundle1.5.zip /drone/deploy/${DRONE_BRANCH}/rotbd1.5c_latest.zip
    volumes:
      - /root/studynator/nginx-fs/private/rotbd/builds/branches:/drone/deploy


