workspace:
  base: /rotbd
  path: /${DRONE_REPO_SLUG}/

pipeline:
  pre-process:
    image: docker.dock1.spaceway.network/bzone/bztools:latest
    pull: true
    when:
      event:
        - push
        - tag

    commands:
      - mkdir /tmp/files
      - mkdir /tmp/lua
      - find /rotbd -type f \( -name "*.lua" -o -name "*.squish" \) -exec cp {} /tmp/lua \;
      - python3 /bztools/luaSquish.py /tmp/lua -r
      - find /rotbd -not -ipath '*/\.*' -not -name '*.lua' -not -name '*.bin' -type f -exec cp {} /tmp/files \;
      - find /tmp/lua -name '*.lua' -type f -exec mv {} /tmp/files \;
      - python3 /bztools/textToSpeech.py /tmp/files
      - python3 /bztools/crlf_fixer.py /tmp/files
      - mkdir -p /rotbd/output
      - zip -j -r /rotbd/output/bundle.zip /tmp/files
      - find -type f -name '*.bzn' -exec python3 /bztools/bznDown.py {} {} \;
      - zip -j -r /rotbd/output/bundle1.5.zip /tmp/files

  upload:
    image: docker.dock1.spaceway.network/bzone/bztools:latest
    pull: true
    when:
      event:
        - push
        - tag
    commands:
      - mkdir -p /builds/branches/${DRONE_BRANCH} || true
      - FILE_COUNT=$(ls /builds/branches/${DRONE_BRANCH} | wc -l) || true
      - mv /builds/branches/${DRONE_BRANCH}/rotbd_latest.zip /builds/branches/${DRONE_BRANCH}/rotbd_"$FILE_COUNT".zip || true
      - cp /rotbd/output/bundle.zip /builds/branches/${DRONE_BRANCH}/rotbd_latest.zip || true
      - mv /builds/branches/${DRONE_BRANCH}/rotbd1.5c_latest.zip /builds/branches/${DRONE_BRANCH}/rotbd1.5c_"$FILE_COUNT".zip || true
      - cp /rotbd/output.5.zip /builds/branches/${DRONE_BRANCH}/rotbd1.5c_latest.zip || true
      - cp -f /tmp/bundle.zip /builds/releases/rotbd_${DRONE_TAG}.zip
      - cp -f /tmp/bundle1.5.zip /builds/releases/rotbd1.5c_${DRONE_TAG}.zip
      - ln -f /builds/releases/rotbd_${DRONE_TAG}.zip /builds/releases/rotbd_latest.zip
      - ln -f /builds/releases/rotbd1.5c_${DRONE_TAG}.zip /builds/releases/rotbd1.5c_latest.zip
    volumes:
      - /srv/data/caddy/media/public/rotbd/builds:/builds


  notification-success:
    image: docker.dock1.spaceway.network/bzone/bztools:latest
    secrets: [ webhook ]
    when:
      event: [ tag ]
      status: [ success ]
    commands:
      - python3 /bztools/webhook.py /rotbd/.webhook.payload $${WEBHOOK} -kv "status=SUCCESS" "tag=${DRONE_TAG}" "buildlink=${DRONE_BUILD_LINK}" "repolink=${DRONE_REPO_LINK}" "repo=${DRONE_REPO_NAME}" "event=${DRONE_BUILD_EVENT}"
  
  notification-fail:
    image: docker.dock1.spaceway.network/bzone/bztools:latest
    secrets: [ webhook ]
    when:
      event: [ tag ]
      status: [ fail ]
    commands: 
      - python3 /bztools/webhook.py /rotbd/.webhook.fail $${WEBHOOK} -kv "status=FAIL" "tag=${DRONE_TAG}" "buildlink=${DRONE_BUILD_LINK}" "repolink=${DRONE_REPO_LINK}" "repo=${DRONE_REPO_NAME}" "event=${DRONE_BUILD_EVENT}"
    

