workspace:
  base: /rotbd
  path: /${DRONE_REPO_SLUG}/

pipeline:
  pre-process:
    image: docker.faavne.no/bzone/bztools:latest
    pull: true
    when:
      event:
        - push
        - tag
      branch:
        - master
    commands:
      - mkdir /tmp/files
      - mkdir /tmp/lua
      - find /rotbd -type f \( -name "*.lua" -o -name "*.squish" \) -exec cp {} /tmp/lua \;
      - python3 /bztools/luaSquish.py /tmp/lua -r
      - find /rotbd -not -ipath '*/\.*' -not -name '*.lua' -not -name '*.bin' -type f -exec cp {} /tmp/files \;
      - find /tmp/lua -name '*.lua' -type f -exec mv {} /tmp/files \;
      - python3 /bztools/textToSpeech.py /tmp/files
      - python3 /bztools/crlf_fixer.py /tmp/files
      - mkdir -p /rotbd/output
      - zip -j -r /rotbd/output/bundle.zip /tmp/files
      - find -type f -name '*.bzn' -exec python3 /bztools/bznDown.py {} {} \;
      - zip -j -r /rotbd/output/bundle1.5.zip /tmp/files

  snapshot-branch:
    group: deploy
    image: docker.faavne.no/bzone/bztools:latest
    when:
      event:
        - push
      branch:
        - master
        
    commands:
      - mkdir -p /drone/deploy/${DRONE_BRANCH} || true
      - FILE_COUNT=$(ls /drone/deploy/${DRONE_BRANCH} | wc -l) || true
      - mv /drone/deploy/${DRONE_BRANCH}/rotbd_latest.zip /drone/deploy/${DRONE_BRANCH}/rotbd_"$FILE_COUNT".zip || true
      - cp /rotbd/output/bundle.zip /drone/deploy/${DRONE_BRANCH}/rotbd_latest.zip || true
      - mv /drone/deploy/${DRONE_BRANCH}/rotbd1.5c_latest.zip /drone/deploy/${DRONE_BRANCH}/rotbd1.5c_"$FILE_COUNT".zip || true
      - cp /rotbd/output/bundle1.5.zip /drone/deploy/${DRONE_BRANCH}/rotbd1.5c_latest.zip || true
    volumes:
      - /mnt/nginx-fs/files/private/rotbd/builds/branches:/drone/deploy

  release:
    group: deploy
    image: docker.faavne.no/bzone/bztools:latest
    when:
      event:
        - tag
    commands:
      - \cp -f /rotbd/output/bundle.zip /drone/deploy/rotbd_${DRONE_TAG}.zip || true
      - \cp -f /rotbd/output/bundle1.5.zip /drone/deploy/rotbd1.5c_${DRONE_TAG}.zip || true
    volumes:
      - /mnt/nginx-fs/files/private/rotbd/builds/releases:/drone/deploy

  notification-success:
    image: docker.faavne.no/bzone/bztools:latest
    secrets: [ webhook ]
    when:
      event: [ tag ]
      status: [ success ]
    commands:
      - python3 /bztools/webhook.py /rotbd/.webhook.payload $${WEBHOOK} -kv "status=SUCCESS" "tag=${DRONE_TAG}" "buildlink=${DRONE_BUILD_LINK}" "repolink=${DRONE_REPO_LINK}" "repo=${DRONE_REPO_NAME}" "event=${DRONE_BUILD_EVENT}"
  
  notification-fail:
    image: docker.faavne.no/bzone/bztools:latest
    secrets: [ webhook ]
    when:
      event: [ tag ]
      status: [ fail ]
    commands: 
      - python3 /bztools/webhook.py /rotbd/.webhook.fail $${WEBHOOK} -kv "status=FAIL" "tag=${DRONE_TAG}" "buildlink=${DRONE_BUILD_LINK}" "repolink=${DRONE_REPO_LINK}" "repo=${DRONE_REPO_NAME}" "event=${DRONE_BUILD_EVENT}"
    

